Repository spacetelescope/hlapipeline, pull requests merged in 2018-12, with the labels that each got.

#32 Tweakwcs replacement code initial pull
  hlapipeline/alignimages.py
  hlapipeline/hlapipeline.py
  hlapipeline/utils/astrometric_utils.py
Labels: enhancement

#34 Add catalog tests
  hlapipeline/alignimages.py
  hlapipeline/utils/astrometric_utils.py
  tests/test_extract.py
Labels: enhancement, testing

#35 Jira hla 120 - Evaluate the viability of a dataset for alignment processing
  hlapipeline/utils/filter.py
Labels: bug

#37 Add tweakwcs tests
  hlapipeline/alignimages.py
  hlapipeline/utils/astrometric_utils.py
  tests/test_extract.py
Labels: enhancement, testing

#41 Protect against writing a source catalog table with zero content.
  hlapipeline/alignimages.py
Labels: bug

#44 New RMS computations working
  hlapipeline/alignimages.py
Labels: bug
