Repository spacetelescope/hlapipeline, pull requests merged in 2018-11, with the labels that each got.

#16 Add initial version of notebook
  docs/notebook/create_gaia_catalog.ipynb
Labels: documentation

#25 If no FLCs available, retrieve FLTs instead.
  hlapipeline/utils/astroquery_utils.py
Labels: enhancement

#26 Update limit to be detector specific, use GAIADR2
  hlapipeline/utils/astrometric_utils.py
  tests/base_test.py
  tests/test_align.py
Labels: enhancement, testing

#27 Initial version of catalog generation code
  hlapipeline/data/alpha_lyr_stis_008.fits
  hlapipeline/utils/astrometric_utils.py
  hlapipeline/utils/bitmask.py
Labels: enhancement

#29 Re-apply new catalog default
  hlapipeline/utils/astrometric_utils.py
Labels: bug

#30 Initial version of design docs
  docs/design.rst
  docs/index.rst
Labels: documentation, enhancement

#31 Update readme tests
  README.rst
Labels: documentation, enhancement, testing
