Repository spacetelescope/hlapipeline, pull requests merged in 2018-10, with the labels that each got.

#1 Copy Drizzlepac Jenkinsfile
  Jenkinsfile
Labels: enhancement

#2 Address code review comments about tests
  tests/test_align.py
Labels: testing

#3 Initial attempt to add BIGDATA to Jenkinsfile
  Jenkinsfile
  hlapipeline/align_to_gaia.py
  setup.py
  tests/base_classes.py
  tests/base_test.py
  tests/test_align.py
Labels: testing

#5 Address code review for PR#3
  Jenkinsfile
  tests/test_align.py
Labels: enhancement, testing

#6 Add astroquery
  Jenkinsfile
  hlapipeline/utils/astroquery_utils.py
  setup.py
  tests/base_classes.py
  tests/base_test.py
  tests/test_align.py
Labels: enhancement, testing

#10 Function to extract random entries (lines) from a CSV file
  hlapipeline/utils/catalog_utils.py
Labels: enhancement

#13 Update run_align method, add test
  Jenkinsfile
  hlapipeline/align_to_gaia.py
  tests/base_test.py
  tests/test_align.py
Labels: bug

#8 Fix logic for downloading ref files
  hlapipeline/align_to_gaia.py
  hlapipeline/utils/astrometric_utils.py
  tests/base_test.py
Labels: bug, testing

#11 [WIP] Created test to process a random list of datasets
  tests/test_align.py
Labels: enhancement, testing

#17 Capture the exceptions for diagnostic purposes
  tests/test_align.py
Labels: enhancement
