Repository spacetelescope/hlapipeline, pull requests merged in 2019-01, with the labels that each got.

#46 Simplified and corrected logic in get_and_check_data
  hlapipeline/alignimages.py
Labels: bug

#47 Fix import error in test_hlapipeline
  tests/test_hlapipeline.py
Labels: bug, testing

#48 Add a display of Git revision information (current branch name, current commit hash)
  hlapipeline/alignimages.py
  hlapipeline/utils/get_git_rev_info.py
Labels: enhancement

#49 Ignore magnitudes from astrometric catalog
  hlapipeline/utils/astrometric_utils.py
Labels: bug

#52 Check additional keywords for evaluation and minor improvements.
  hlapipeline/utils/filter.py
Labels: enhancement

#43 Source detection with daostarfind
  hlapipeline/alignimages.py
  hlapipeline/utils/astrometric_utils.py
  tests/test_extract.py
Labels: enhancement

#54 Add code to compute RMS_RA, RMS_DEC
  hlapipeline/alignimages.py
  hlapipeline/utils/astrometric_utils.py
Labels: enhancement

#55 Make starfind algorithm 4-5 times faster
  hlapipeline/alignimages.py
  hlapipeline/utils/astrometric_utils.py
Labels: enhancement

#59 From master special big test
  hlapipeline/alignimages.py
  hlapipeline/utils/catalog_utils.py
  hlapipeline/utils/filter.py
  tests/test_bigRandom.py
Labels: bug, enhancement

#57 DMS-117: Fixed bug in basic looping logic of alignimages.py
  hlapipeline/alignimages.py
  hlapipeline/utils/filter.py
Labels: bug

#60 Only update table upon successful fit
  hlapipeline/alignimages.py
Labels: bug

#61 Ensure filteredTable is populated properly and always returned, updat…
  hlapipeline/alignimages.py
  tests/test_bigRandom.py
Labels: bug, enhancement

#63 Fixed best_meta logic, simplified best_meta updates
  hlapipeline/alignimages.py
Labels: bug

#56 Hla 163 return headerlet files
  hlapipeline/alignimages.py
Labels: enhancement

#68 Handle no sources found in image in the same way as not enough sources found.
  hlapipeline/alignimages.py
Labels: bug

#69 Fix to break out of two for loops when fix solution < MAX_FIT_RMS
  hlapipeline/alignimages.py
Labels: bug

#70 Implemented try/except around matching functionality.
  hlapipeline/alignimages.py
Labels: bug

#71 Fix Exceptions in background estimation
  hlapipeline/utils/astrometric_utils.py
Labels: enhancement
